{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 01:29:27.927284", "error": "django.core.exceptions.FieldError", "errormsg": "Cannot resolve keyword 'create_time_gt' into field. Choices are: create_time, id, income, introducer, is_deleted, money, name, phone, trade, update_time", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 39, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 01:34:45.749976", "error": "django.core.exceptions.FieldError", "errormsg": "Cannot resolve keyword 'price' into field. Choices are: costomer, costomer_id, create_time, id, is_deleted, money, type, update_time", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 42, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 01:43:36.610259", "error": "TypeError", "errormsg": "unsupported operand type(s) for -: 'datetime.date' and 'int'", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 44, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 01:46:48.494119", "error": "NameError", "errormsg": "name 'date' is not defined", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 43, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 01:47:03.264285", "error": "NameError", "errormsg": "name 'oneday' is not defined", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 44, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 01:47:04.164004", "error": "NameError", "errormsg": "name 'oneday' is not defined", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 44, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 16:24:48.859594", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 57, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 16:30:37.002665", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 57, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 16:34:17.598005", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 64, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 16:45:06.785145", "error": "TypeError", "errormsg": "can only concatenate str (not \"datetime.datetime\") to str", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 47, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 16:45:58.409980", "error": "TypeError", "errormsg": "can only concatenate str (not \"datetime.datetime\") to str", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 50, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 17:19:40.011960", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 74, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 17:54:00.474683", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 80, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 17:57:36.514147", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 80, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 18:43:37.803828", "error": "TypeError", "errormsg": "descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'str' object", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 45, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 18:45:58.561508", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 81, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 19:05:07.538901", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 81, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 19:14:39.532196", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 81, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 19:16:38.382442", "error": "TypeError", "errormsg": "can only concatenate str (not \"builtin_function_or_method\") to str", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 49, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 19:34:04.942725", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 77, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 20:21:33.752980", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 78, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 20:29:08.659915", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 82, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 20:30:58.165621", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 78, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 20:34:59.213092", "error": "ValueError", "errormsg": "month must be in 1..12", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 78, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 20:43:42.895413", "error": "TypeError", "errormsg": "list indices must be integers or slices, not str", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 94, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 20:51:34.721470", "error": "TypeError", "errormsg": "'builtin_function_or_method' object is not iterable", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 97, in get"], "method": "GET", "url": "/ztx/recharge", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:27:45.298776", "error": "ValueError", "errormsg": "The QuerySet value for an exact lookup must be limited to one result using slicing.", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 134, in get"], "method": "GET", "url": "/ztx/consume", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:29:22.037188", "error": "django.core.exceptions.FieldError", "errormsg": "Cannot resolve keyword 'product.id' into field. Choices are: costomer, costomer_id, create_time, id, is_deleted, product, product_id, update_time", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 134, in get"], "method": "GET", "url": "/ztx/consume", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:32:52.127315", "error": "django.core.exceptions.FieldError", "errormsg": "Cannot resolve keyword 'product.price' into field. Choices are: costomer, costomer_id, create_time, id, is_deleted, product, product_id, update_time", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 134, in get"], "method": "GET", "url": "/ztx/consume", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:35:58.896740", "error": "django.core.exceptions.FieldError", "errormsg": "Cannot resolve keyword 'price' into field. Choices are: costomer, costomer_id, create_time, id, is_deleted, product, product_id, update_time", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 134, in get"], "method": "GET", "url": "/ztx/consume", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:46:20.434008", "error": "django.core.exceptions.FieldError", "errormsg": "Cannot resolve keyword 'product' into field. Choices are: costomer, costomer_id, create_time, id, is_deleted, money, type, update_time", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 196, in get"], "method": "GET", "url": "/ztx/consume", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:48:45.275948", "error": "django.core.exceptions.FieldError", "errormsg": "Cannot resolve keyword 'product' into field. Choices are: costomer, costomer_id, create_time, id, is_deleted, money, type, update_time", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 196, in get"], "method": "GET", "url": "/ztx/consume", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:48:56.766526", "error": "ztx.models.MultipleObjectsReturned", "errormsg": "get() returned more than one Income -- it returned more than 20!", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 196, in get"], "method": "GET", "url": "/ztx/consume", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:49:08.101708", "error": "django.core.exceptions.FieldError", "errormsg": "Cannot resolve keyword 'product' into field. Choices are: costomer, costomer_id, create_time, id, is_deleted, money, type, update_time", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 196, in get"], "method": "GET", "url": "/ztx/consume", "user": null, "params": {}, "data": {}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2020-12-11 21:50:41.395978", "error": "redis.exceptions.ConnectionError", "errormsg": "Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.", "errorpath": ["File \"D:\\Projects\\ztx\\server\\rbac\\views.py\", line 80, in post", "File \"D:\\Projects\\ztx\\server\\libs\\authtication.py\", line 43, in create_token"], "method": "POST", "url": "/rbac/login", "user": null, "params": {}, "data": {"username": "admin", "password": "admin"}}
