{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2021-03-09 13:21:22.611178", "error": "django.db.utils.IntegrityError", "errormsg": "UNIQUE constraint failed: ztx_costomer.phone", "errorpath": [], "method": "POST", "url": "/ztx/costomer/", "user": null, "params": {}, "data": {"id": "", "name": "123", "phone": "", "money": 0, "introducer": ""}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2021-03-09 15:38:09.446806", "error": "django.db.utils.IntegrityError", "errormsg": "UNIQUE constraint failed: ztx_costomer.phone", "errorpath": [], "method": "POST", "url": "/ztx/costomer/", "user": null, "params": {}, "data": {"id": "", "name": "阿斯蒂芬", "phone": "", "money": 0, "introducer": ""}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2021-03-09 15:38:20.120589", "error": "django.db.utils.IntegrityError", "errormsg": "UNIQUE constraint failed: ztx_costomer.phone", "errorpath": [], "method": "POST", "url": "/ztx/costomer/", "user": null, "params": {}, "data": {"id": "", "name": "水电费", "phone": "", "money": 0, "introducer": ""}}
{"code": 10000, "msg": "服务器内部错误", "@timestamp": "2021-03-09 15:56:16.534179", "error": "KeyError", "errormsg": "'amount'", "errorpath": ["File \"D:\\Projects\\ztx\\server\\ztx\\views.py\", line 209, in post"], "method": "POST", "url": "/ztx/consume", "user": null, "params": {}, "data": {"id": 4, "name": "水电费", "product_id": 1, "price": 11}}
